/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BookingWindow.java
 *
 * Created on 15-May-2011, 16:32:48
 */
package gui;

import businesslogic.BookingController;
import domain.Customer;
import domain.Discount;
import domain.Route;
import domain.Ticket;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndreiM
 */
public class BookingWindow extends javax.swing.JFrame {

    private String status="";
    private String view="";
    private String cnp;
    
    /** Creates new form BookingWindow */
    public BookingWindow(String view,String cnp) {
        initComponents();
        if(view.compareTo("terminal")==0){
            this.view="terminal";
            this.cnp="";
            jLabel11.setVisible(false);
            jComboBox5.setVisible(false);
        }
        if(view.compareTo("cashier")==0){
            this.view="cashier";
            this.cnp=cnp;
            jLabel11.setVisible(true);
            jComboBox5.setVisible(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Departure Station");

        jTextField1.setColumns(20);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Arrival Station");

        jTextField2.setColumns(20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose:", "Personal", "Accelerat", "Rapid", "Intercity" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Type of train (optional)");

        jLabel4.setText("Choose class of train (optional)");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Second", "First" }));

        jLabel5.setText("Maximum price (optional)");

        jLabel6.setText("Seat preference (optional)");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Window Seat", "Corridor Seat" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Forward Facing", "Backward Facing" }));

        jLabel7.setText("Departure hour (hh:mm) (optional)");

        jTextField4.setColumns(20);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Arrival hour (hh:mm) (optional)");

        jLabel9.setText("Intermediary Station (optional)");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Discount:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose:", "Student", "Soldier", "Retired" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(47, 47, 47)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(327, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(185, 185, 185)
                .addComponent(jButton1)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departure Time", "Arrival Time", "Departure Station", "Arrival Station", "Train Type", "Distance", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Pay Ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel10.setText("");
        status="";
        String trainType=jComboBox1.getSelectedItem().toString();
        String intermediaryStation="";
        
        if(jTextField6.getText().compareTo("")!=0){
            intermediaryStation=jTextField6.getText();
        }
        
        int departureHourLow=0,departureHourHigh=24;
        int arrivalHourLow=0,arrivalHourHigh=24;
        
        if(jTextField4.getText().compareTo("")!=0){   
        
            int departureHour=Integer.parseInt(jTextField4.getText().split(":")[0]);
            int departureMin=Integer.parseInt(jTextField4.getText().split(":")[1]);
                     
        //    System.out.println("arrival="+arrivalHour+" departure="+departureHour);
        
            if(departureMin>30){
                departureHourLow=departureHour;
                departureHourHigh=departureHour+2;
            }
            else{
                departureHourLow=departureHour-1;
                departureHourHigh=departureHour+1;
            }
        }
        if(jTextField5.getText().compareTo("")!=0){
            
            int arrivalHour= Integer.parseInt(jTextField5.getText().split(":")[0]);
            int arrivalMin= Integer.parseInt(jTextField5.getText().split(":")[1]);
            
            if(arrivalMin>30){
                arrivalHourLow=arrivalHour;
                arrivalHourHigh=arrivalHour+2;
            }
            else{
                arrivalHourLow=arrivalHour-1;
                arrivalHourHigh=arrivalHour+1;
            }
        }
        
        if(intermediaryStation.compareTo("")==0){
            status="single";
            ArrayList<Route> listRoutes=BookingController.checkTrain(jTextField1.getText(), jTextField2.getText(),trainType,departureHourLow,departureHourHigh,arrivalHourLow,arrivalHourHigh);
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            int maxPrice=10000;
            if(jTextField3.getText().compareTo("")!=0){
                maxPrice=Integer.parseInt(jTextField3.getText());
            }       
      //      System.out.println(maxPrice);
      //      System.out.println("Count:"+model.getRowCount());
            ArrayList<Ticket> myTickets=new ArrayList<Ticket>();
            while(model.getRowCount()!=0){
                model.removeRow(model.getRowCount()-1);
            }
            if(listRoutes==null){
        //       System.out.println("NULL");
               String intermediateStation=BookingController.checkIntermediateStation(jTextField1.getText(), jTextField2.getText());
               if(intermediateStation==null){
                    jLabel10.setText("No match was found. There does not exist a composed entry");
               }
               else{
                   jLabel10.setText("We do not have a train from "+jTextField1.getText()+" to "+jTextField2.getText()+", instead we have a train from "+jTextField1.getText()+" to "+intermediateStation+" and then from "+intermediateStation+" to "+jTextField2.getText());
                   jTextField6.setText(intermediateStation);
               }
          //     System.out.println(intermediateStation);
            }
            else{
                Discount myDiscount=new Discount("no",1);
                if(view.compareTo("cashier")==0){
                    if(jComboBox5.getSelectedItem().toString().compareTo("Student")==0){
                        myDiscount=new Discount("Student",0.8);
               //         discount=0.8; // 20 percent discount
                    }
                    if(jComboBox5.getSelectedItem().toString().compareTo("Soldier")==0){
                        myDiscount=new Discount("Soldier",0.6);
                 //       discount=0.6; // 40 percent discount
                    }
                    if(jComboBox5.getSelectedItem().toString().compareTo("Retired")==0){
                        myDiscount=new Discount("Retired",0.9);
                 //       discount=0.9; // 10 percent discount
                    }
                }
                Customer myCustomer=null;
                if(view.compareTo("cashier")==0){
                    myCustomer=BookingController.getCustomer(cnp);
                }
                if(myCustomer==null){
                    System.out.println("NULL");
                }
          //      System.out.println(myCustomer.toString());
                myTickets=BookingController.createTickets(jComboBox2.getSelectedItem().toString(),jComboBox3.getSelectedItem().toString(),jComboBox4.getSelectedItem().toString(),maxPrice,myDiscount,myCustomer);
        //        System.out.println(BookingController.getMyRouteList().size());
       //         System.out.println(myTickets.size());
                int index=0;
                for(Route r:listRoutes){
                    model.addRow(new Object[]{r.getDepartureTime(),r.getArrivalTime(),r.getListStation().getListStation().get(0).getName(),r.getListStation().getListStation().get(1).getName(),r.getTrain().getType(),r.getDistance(),myTickets.get(index).getPrice()});          
                    index++;
                }

            jTable1.setModel(model);
            }
        }
        else{
            status="double";
            ArrayList<Route> listRoutes=BookingController.checkTrain(jTextField1.getText(), intermediaryStation,trainType,departureHourLow,departureHourHigh,0,24);
            ArrayList<Route> addRoutes=BookingController.checkTrain(intermediaryStation, jTextField2.getText(),trainType,0,24,arrivalHourLow,arrivalHourHigh);
            if(addRoutes!=null){
         //       System.out.println(addRoutes);
                if(listRoutes==null){
                    listRoutes=addRoutes;
                }
                else{
                    listRoutes.addAll(addRoutes);
                }
            }
            if(listRoutes!=null)
                BookingController.setMyRouteList(listRoutes);
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            int maxPrice=10000;
            if(jTextField3.getText().compareTo("")!=0){
                maxPrice=Integer.parseInt(jTextField3.getText());
            }       
      //      System.out.println(maxPrice);
      //      System.out.println("Count:"+model.getRowCount());
            ArrayList<Ticket> myTickets=new ArrayList<Ticket>();
            while(model.getRowCount()!=0){
                model.removeRow(model.getRowCount()-1);
            }
            if(listRoutes==null){
    //           System.out.println("NULL");
            }
            else{
          //      double discount=1;
                Discount myDiscount=new Discount("no",1);
                if(view.compareTo("cashier")==0){
                    if(jComboBox5.getSelectedItem().toString().compareTo("Student")==0){
                        myDiscount=new Discount("Student",0.8);
               //         discount=0.8; // 20 percent discount
                    }
                    if(jComboBox5.getSelectedItem().toString().compareTo("Soldier")==0){
                        myDiscount=new Discount("Soldier",0.6);
                 //       discount=0.6; // 40 percent discount
                    }
                    if(jComboBox5.getSelectedItem().toString().compareTo("Retired")==0){
                        myDiscount=new Discount("Retired",0.9);
                 //       discount=0.9; // 10 percent discount
                    }
                }
                Customer myCustomer=null;
                if(view.compareTo("cashier")==0){
                    myCustomer=BookingController.getCustomer(cnp);
                }
                myTickets=BookingController.createTickets(jComboBox2.getSelectedItem().toString(),jComboBox3.getSelectedItem().toString(),jComboBox4.getSelectedItem().toString(),maxPrice,myDiscount,myCustomer);
                int index=0;
                for(Route r:listRoutes){
                    model.addRow(new Object[]{r.getDepartureTime(),r.getArrivalTime(),r.getListStation().getListStation().get(0).getName(),r.getListStation().getListStation().get(1).getName(),r.getTrain().getType(),r.getDistance(),myTickets.get(index).getPrice()});          
                    index++;
                }

            jTable1.setModel(model);
            }
            jLabel10.setText("Please select two routes in order to print the ticket.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!=(-1)){
            String myCnp=cnp;
            if(view.compareTo("cashier")==0 && jComboBox5.getSelectedItem().toString().compareTo("Choose:")==0){
                myCnp="";
            }
            if(status.compareTo("single")==0){
          //      System.out.println(jTable1.getSelectedRow());
                BookingController.setSelectedTicket(jTable1.getSelectedRow());                
                PaymentMethodWindow myPayment=new PaymentMethodWindow(status,myCnp,cnp);
                myPayment.setVisible(true);
            }
            if(status.compareTo("double")==0){
         //       System.out.println(jTable1.getSelectedRow());
                int [] selectedRows=jTable1.getSelectedRows();
                BookingController.setSelectedTickets(selectedRows[0],selectedRows[1]);
                PaymentMethodWindow myPayment=new PaymentMethodWindow(status,myCnp,cnp);
                myPayment.setVisible(true);
            }
        }
 /*       
        if(jTable1.getSelectedRow()!=(-1)){
            String myCnp=cnp;
            if(view.compareTo("cashier")==0 && jComboBox5.getSelectedItem().toString().compareTo("Choose:")==0){
                myCnp="";
            }
            if(status.compareTo("single")==0){
          //      System.out.println(jTable1.getSelectedRow());
                BookingController.setSelectedTicket(jTable1.getSelectedRow());                
                PrintTicketWindow myPrint=new PrintTicketWindow(status,myCnp);
                myPrint.setVisible(true);
            }
            if(status.compareTo("double")==0){
         //       System.out.println(jTable1.getSelectedRow());
                int [] selectedRows=jTable1.getSelectedRows();
                BookingController.setSelectedTickets(selectedRows[0],selectedRows[1]);
                PrintTicketWindow myPrint1=new PrintTicketWindow(status,myCnp);
                myPrint1.setVisible(true);
        /*        PrintTicketWindow myPrint1=new PrintTicketWindow("double1");
                myPrint1.setVisible(true);
                PrintTicketWindow myPrint2=new PrintTicketWindow("double2");
                myPrint2.setVisible(true); 
            }
        } */
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
