/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrintTicketWindow.java
 *
 * Created on 16-May-2011, 18:01:07
 */
package gui;

import businesslogic.BookingController;

/**
 *
 * @author AndreiM
 */
public class PrintTicketWindow extends javax.swing.JFrame {

    /** Creates new form PrintTicketWindow */
    public PrintTicketWindow(String status,String cnp) {
        initComponents();
        if(status.compareTo("single")==0){
            jLabel2.setText(String.valueOf(BookingController.getMyTicket().getRoute().getTrain().getId()));
            jLabel5.setText(BookingController.getMyTicket().getRoute().getTrain().getType());
            jLabel6.setText(String.valueOf(BookingController.getMyTicket().getSeat().getNumber()));
            jLabel9.setText(BookingController.getMyTicket().getSeat().getPlacement());
            jLabel10.setText(BookingController.getMyTicket().getSeat().getDirection());
            BookingController.updateRouteTicket();
        }
 /*       if(status.compareTo("double1")==0){
            jLabel2.setText(String.valueOf(BookingController.getMyTickets().get(0).getRoute().getTrain().getId()));
            jLabel5.setText(BookingController.getMyTickets().get(0).getRoute().getTrain().getType());
            jLabel6.setText(String.valueOf(BookingController.getMyTickets().get(0).getSeat().getNumber()));
            jLabel9.setText(BookingController.getMyTickets().get(0).getSeat().getPlacement());
            jLabel10.setText(BookingController.getMyTickets().get(0).getSeat().getDirection());
        } */
        if(status.compareTo("double")==0){
            jLabel2.setText(String.valueOf(BookingController.getMyTickets().get(0).getRoute().getTrain().getId())+"|"+String.valueOf(BookingController.getMyTickets().get(1).getRoute().getTrain().getId()));
            jLabel5.setText(BookingController.getMyTickets().get(0).getRoute().getTrain().getType()+"|"+BookingController.getMyTickets().get(1).getRoute().getTrain().getType());
            jLabel6.setText(String.valueOf(BookingController.getMyTickets().get(0).getSeat().getNumber())+"|"+String.valueOf(BookingController.getMyTickets().get(1).getSeat().getNumber()));
            jLabel9.setText(BookingController.getMyTickets().get(0).getSeat().getPlacement()+"|"+BookingController.getMyTickets().get(1).getSeat().getPlacement());
            jLabel10.setText(BookingController.getMyTickets().get(0).getSeat().getDirection()+"|"+BookingController.getMyTickets().get(1).getSeat().getDirection());
            BookingController.updateRouteTickets();
        }
        if(cnp.compareTo("")==0){
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
        }
        else{
            if(status.compareTo("single")==0){
                jLabel12.setText(BookingController.getMyTicket().getClient().getIdc().getCNP());
            }
            if(status.compareTo("double")==0){
                jLabel12.setText(BookingController.getMyTickets().get(0).getClient().getIdc().getCNP());
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Train ID:");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Train Type:");

        jLabel4.setText("Seat Number:");

        jLabel7.setText("Placement:");

        jLabel8.setText("Direction:");

        jLabel11.setText("CNP (disount ticket):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addComponent(jLabel8))
                        .addContainerGap(207, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
